name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ls
      run: ls
    - name: create build directory
      run: mkdir build
    - name: cd build 
      run: cd build
    - name: create Makefiles
      run: cmake ..
    - name: build
      run: make
    - name: test
      run: ./test
